### ISSUE TITLE
[distensibility]: Introduce a strategy to take into account the vessels distensibility 

### ISSUE THREAD

**Issue by clambr** [Franculino/microBlooM#25]
A pressure–area relationship (linear & non-linear) is used to model the elasticity of the vessel. 

**Important Literature:**
- Padmos, Raymond M., et al. "Modelling collateral flow and thrombus permeability during acute ischaemic stroke." Journal of the Royal Society Interface 19.195 (2022): 20220649.
- Absi, Rafik. "Revisiting the pressure-area relation for the flow in elastic tubes: Application to arterial vessels." Series on Biomechanics 32 (2018): 47-59.

**Comment by epprob** [comment]
Further literature:
Ali Daher a,*, Stephen Payne b: A network-based model of dynamic cerebral autoregulation

**Comment by epprob** [comment]
I started a new branch to include some vessel distensibility which is required for the rebuttal of the LMC paper. Maybe, the overall structure can be of help for future, more sophisticated implementations..
